const INGREDIENTS_ACTIONS = {
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  RESET_INGREDIENTS: "RESET_INGREDIENTS",
};

const PRICE_ACTIONS = {
  CALCULATE_PRICE: "CALCULATE_PRICE",
  RESET_PRICE: "RESET_PRICE",
};

export { INGREDIENTS_ACTIONS, PRICE_ACTIONS };
